{% set name = "sentencepiece" %}
{% set version = "0.1.94" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  host:
    - pip
    - python

  run:
    - python
    #- libstdcxx-ng
    #- libgcc-ng

test:
  imports:
    - sentencepiece
  requires:
    - pip

about:
  home: https://github.com/google/sentencepiece
  summary: SentencePiece python wrapper
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jph00
