{% set name = "timm" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/timm-{{ version }}.tar.gz
  sha256: 1d4b55778e74ace21f39a1461c7075632ed5895532d11b53a85d1bedac0c5d77

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch >=1.4
    - torchvision
    - dataclasses # py36

test:
  imports:
    - timm
    - timm.data

about:
  home: https://github.com/rwightman/pytorch-image-models
  summary: PyTorch Image Models
  license: Apache-2.0
  license_family: APACHE
  summary: PyTorch Image Models
  doc_url: https://pypi.org/project/timm/
  dev_url: https://github.com/rwightman/pytorch-image-models

extra:
  recipe-maintainers:
    - jph00

