name: anacopy
on:
  workflow_dispatch:
schedule:
  - cron: "* */6 * * *"

jobs:
  copy:
    env:
      FASTCHAN: ${{ secrets.FASTCHAN }}
    strategy:
      fail-fast: false
      matrix: {py: [3.6, 3.7, 3.8]}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash get_deps.sh ${{ matrix.py }}
