name: anacopy
on:
  workflow_dispatch:
  schedule:
    - cron: "* */6 * * *"

jobs:
  copy:
    env:
      FASTCHAN: ${{ secrets.FASTCHAN }}
    strategy:
      fail-fast: false
      matrix:
        py: [3.6, 3.7, 3.8]
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash get_deps.sh ${{ matrix.py }}
