name: anacopy2
on:
  workflow_dispatch:

jobs:
  copy:
    env:
      FASTCHAN: ${{ secrets.FASTCHAN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        bash get_deps.sh 3.6
        bash get_deps.sh 3.7
        bash get_deps.sh 3.8

