name: anacopy

on:
  workflow_dispatch:

jobs:
  copy:
    env:
      FASTCHAN: ${{ secrets.FASTCHAN }}
    strategy:
      matrix:
        py: [3.6, 3.7, 3.8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash get_deps.sh ${{ matrix.py }}
